### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by saxenamalini** [bendrucker/lambda-cloudformation-response#1]
I can't seem to install it on my mac, the pip versiob I have is 8.1.2

>root# pip install lambda-cloudformation-response
Collecting lambda-cloudformation-response
  Could not find a version that satisfies the requirement lambda-cloudformation-response (from versions: )
No matching distribution found for lambda-cloudformation-response

**Comment by bendrucker** [comment]
This is an npm package you can't download it from pip

**Comment by saxenamalini** [comment]
tried with npm first but got this:

npm install --save lambda-cloudformation-response
npm WARN saveError ENOENT: no such file or directory, open '/private/var/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/private/var/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

**Comment by bendrucker** [comment]
You might not have permission to install there

**Comment by saxenamalini** [comment]
I am logged in as root on my own machine. I am able to install other things.
